name: code-quality
on:
    pull_request:
        branches: 'main'
        types: [opened, synchronize, reopened, ready_for_review]
    push:
        branches: 'main'
jobs:
    code-quality:
        if: github.event.pull_request.draft==false
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              name: workspace setup
            - uses: actions/setup-node@v3
              name: setup node
              with:
                  node-version: '>=16.10.0'
                  cache: 'npm'
                  cache-dependency-path: 'package-lock.json'
