name: code-quality
on: [push]
jobs:
    node-setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '>=16.10.0'
                  cache: 'npm'
                  cache-dependency-path: 'package-lock.json'
    npm-setup:
        runs-on: ubuntu-latest
        needs: node-setup
        steps:
            - run: npm ci
    build:
        runs-on: ubuntu-latest
        needs: npm-setup
        steps:
            - run: npm run build
    typecheck:
        runs-on: ubuntu-latest
        needs: npm-setup
        steps:
            - run: npm run typecheck
